# This rule is not used by the project workspace itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the vc.vc-operator.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/managed-by: kustomize
  name: verifiablecredentialrequest-editor-role
rules:
- apiGroups:
  - vc.vc-operator.io
  resources:
  - verifiablecredentialrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vc.vc-operator.io
  resources:
  - verifiablecredentialrequests/status
  verbs:
  - get
