# This rule is not used by the project workspace itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over vc.vc-operator.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/managed-by: kustomize
  name: verifiablecredentialrequest-admin-role
rules:
- apiGroups:
  - vc.vc-operator.io
  resources:
  - verifiablecredentialrequests
  verbs:
  - '*'
- apiGroups:
  - vc.vc-operator.io
  resources:
  - verifiablecredentialrequests/status
  verbs:
  - get
