apiVersion: vc.vc-operator.io/v1alpha1
kind: CredentialIssuer
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/managed-by: kustomize
  name: credentialissuer-sample
spec:
  # TODO(user): Add fields here
