apiVersion: vc.vc-operator.io/v1alpha1
kind: VerifiableCredentialRequest
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/managed-by: kustomize
  name: verifiablecredentialrequest-sample
spec:
  # TODO(user): Add fields here
